name: Hourly Wind Data Fetch

on:
  schedule:
    - cron: '*/10 * * * *'   # Run every day at 06:00 UTC
  workflow_dispatch:      # Allow manual run

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run data fetch script
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: python fetch_data.py

    - name: Commit and push changes
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@users.noreply.github.com"
        git remote set-url origin https://${{ github.actor }}:${GH_PAT}@github.com/${{ github.repository }}.git

        # Safely stash local changes before pull
        git stash
        git pull origin main --rebase
        git stash pop || true  # apply stash back

        git add data/wind_data.csv
        git commit -m "📈 Hourly wind data update" || echo "No changes to commit"
        git push origin HEAD:main



